// get all sandwich types
GET http://localhost:3000/api/v1/sandwich

// get the sandwich based on id
###
GET http://localhost:3000/api/v1/sandwich/642cb366a36f7d2514e90556


----------------------------------------------------------------
// get all users
###
GET http://localhost:3000/api/v1/users

//get user based on id
###
GET http://localhost:3000/api/v1/users/
