// get all sandwiches
GET http://localhost:3000/sandwich

// create a new sandwich - need authorization
###
POST  http://localhost:3000/sandwich
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4MjI4NTUyNH0.JQz5b9TGqYY4XNj2yr2PQSFPAtpoVLmCN_ZHAk1u2vg
Content-Type: application/json

{
    "name": "Test",
    "price": 8.99,
    "image": "https://i.ibb.co/8rLrM8Y/ham-salad-submarine-sandwich-1339-5908.jpg",
    "description": "A classic sandwich with turkey, bacon, lettuce, and tomato on toasted bread",
    "toppings": [
      { "id" : 1, "name": "Mayonnaise"},
      { "id" : 2, "name": "Mustard"},
      { "id" : 3, "name": "Cheese" },
      { "id" : 4, "name": "Avocado"}
    ],
    "breadType": "Whole Duy"
}

// get the sandwich based on id
###
GET http://localhost:3000/sandwich/642cb366a36f7d2514e90556

// update the sandwich based on id - need authentication
###
PATCH http://localhost:3000/sandwich/642cb366a36f7d2514e9055e3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4MjI4NTUyNH0.JQz5b9TGqYY4XNj2yr2PQSFPAtpoVLmCN_ZHAk1u2vg
Content-Type: application/json

{
    "name": "Test again",
    "price": 8.2
}

// delete the sandwich based on id - need authorization
###
DELETE http://localhost:3000/sandwich/642cb366a36f7d2514e9055e3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTY4MjIwNDc1MH0.j0gkBepSErRDALu58uQSNELmWz878tKgY0KehW9E17k


----------------------------------------------------------------
// get all users - need authorization
###
GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4MjI4NTUyNH0.JQz5b9TGqYY4XNj2yr2PQSFPAtpoVLmCN_ZHAk1u2vg

// get user based on name
###
GET http://localhost:3000/user/Duyhihi

// create a new user
###
POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@gmail.com",
    "password": "Admin123456"
}

// login
###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "name": "admin",
    "password": "Admin123456"
}

// update a user - need authorization
###
PATCH http://localhost:3000/user/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4MjI4NTUyNH0.JQz5b9TGqYY4XNj2yr2PQSFPAtpoVLmCN_ZHAk1u2vg
Content-Type: application/json

{
    "name": "admin",
    "role": "admin",
    "abc": "aaaa"
}

// get all orders - need authorization
###
GET http://localhost:3000/order/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTY4MjIwNTIxOX0.n1NkD96BnygZSNlHILFyOWZX72yKWeIOggPOMVvP6hI

// get all orders from given user_id - need authentication
###
GET http://localhost:3000/order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTY4MjIwNTIxOX0.n1NkD96BnygZSNlHILFyOWZX72yKWeIOggPOMVvP6hI


// create an order - need authentication
###
POST http://localhost:3000/order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4MjIwNTIxOX0.cJMaXWu6-OVXGdNm94zxHYecGrV9pB9WY0zdYCvqh_U
Content-Type: application/json

{
    "customerId": "642f563dde8cef89ac066f0e",
    "items": [
        {
            "_id": "642cb366a36f7d2514e90556",
            "name": "Chicken Caesar Wrap",
            "price": 7.99,
            "image": "https://example.com/chicken-caesar-wrap.jpg",
            "description": "A wrap with grilled chicken, romaine lettuce, Parmesan cheese, and Caesar dressing",
            "toppings": [
                { "id" : 1, "name": "Caesar Dressing", "number" : 1},
                { "id" : 2, "name": "Parmesan Cheese", "number" : 2 },
                { "id" : 3, "name": "Tomato", "number" : 0}
            ]
        }
    ]
}

// delete an order from given Order_id - need authorization
###
DELETE http://localhost:3000/order/64446b9fe39054271a8a6fec
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4MjIwNTIxOX0.cJMaXWu6-OVXGdNm94zxHYecGrV9pB9WY0zdYCvqh_U
